"""empty message

Revision ID: 76cdefd1c5a1
Revises: 41ce2620ecb1
Create Date: 2026-03-21 03:50:52.120242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76cdefd1c5a1'
down_revision: Union[str, None] = '41ce2620ecb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calculations', schema=None) as batch_op:
        #batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))
        ...
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calculations', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###
